paths:
  annotations_csv: "data/raw/flickr_annotations_30k.csv"
  images_dir: "data/raw/flickr30k-images"

data:
  use_split: "train"   # 'train', 'val', 'test', or 'all'
  num_preview: 3  

clean_paths:
  save_dir: "data/processed"

model:
  gpt2_type: "gpt2"           # 'gpt2' (768-dim) or 'gpt2-medium' (1024-dim)
  d_model: 768                # GPT-2 standard hidden size
  num_img_tokens: 4           # Phase 2: Number of "fake word" tokens for the image
  num_unfreeze_layers: 4      # Phase 1: How many transformer blocks to train (top-down)
  dropout: 0.1                # Dropout for the bridge/projection layer

training:
  num_epochs: 20
  batch_size: 8
  lr: 0.0001
  weight_decay: 0.01
  num_workers: 4
  resume_from_checkpoint: True
  use_amp: False

checkpoint:
  dir: checkpoints/
  latest: latest.pth
  best: best.pth

monitoring:
  fixed_image_path: "data/raw/flickr30k-images/1000092795.jpg"
