paths:
  annotations_csv: "data/raw/flickr_annotations_30k.csv"
  images_dir: "data/raw/flickr30k-images"

data:
  use_split: "train"   # 'train', 'val', 'test', or 'all'
  num_preview: 3  

clean_paths:
  save_dir: "data/processed"

model:
  d_model: 512
  n_heads: 8
  num_layers: 3
  dim_feedforward: 2048
  max_seq_len: 129
  dropout: 0.2

training:
  num_epochs: 30
  batch_size: 8
  lr: 0.0001
  weight_decay: 0.01
  num_workers: 4
  resume_from_checkpoint: True
  use_amp: True

checkpoint:
  dir: checkpoints/
  latest: latest.pth
  best: best.pth

monitoring:
  fixed_image_path: "data/raw/flickr30k-images/1000092795.jpg"
