paths:
  annotations_csv: "data/raw/flickr_annotations_30k.csv"
  images_dir: "data/raw/flickr30k-images"

data:
  use_split: "train"   # 'train', 'val', 'test', or 'all'
  num_preview: 3  

clean_paths:
  save_dir: "data/processed"

model:
  d_model: 512
  n_heads: 8
  num_layers: 4
  dim_feedforward: 2048
  max_seq_len: 129
  dropout: 0.1